const choices = {
  do: [
    "Start",
    "Stop",
    "Try more",
    "Do less",
    "Do more",
    "Cut back on",
    "Improve",
    "Finish",
    "Invent",
    "Find",
    "Solve",
    "Investigate",
    "Explore",
    "Discover",
    "End",
    "Retry",
    "Negotiate",
    "Imagine",
    "Consider",
    "Revamp",
    "Learn",
    "Get",
    "Quit",
    "Undermine",
    "Discredit",
    "Review",
    "Destroy",
    "Increase",
    "Decrease",
    "Escape",
    "Tackle",
    "Take advantage of",
    "Break",
    "Build",
    "Search",
    "Conquer",
    "Accurately predict",
    "Regret",
    "Revolutionize",
    "Keep",
    "Practice",
    "Perfect",
    "Prevent",
    "Convince others to",
    "Dominate",
    "See",
    "Reverse",
    "Plagiarize",
    "Steal",
    "Borrow",
    "Save",
    "Delete",
    "Boost",
    "Cook",
    "Be seen",
    "Photograph",
  ],
  what: [
    "farting",
    "running",
    "playa hating",
    "crushing it",
    "eating",
    "hugging",
    "corduroy pants",
    "murder",
    "kickboxing",
    "kickball",
    "chillin'",
    "gambling",
    "lying",
    "lying to myself",
    "stealing",
    "identity theft",
    "sneezing",
    "vandalism",
    "hijinks",
    "lollygagging",
    "mischief",
    "time travel",
    "catfishing",
    "screaming",
    "recycling",
    "brushing teeth",
    "space travel",
    "pulling yourself together",
    "Catching all the Pokemon",
    "devil worshiping",
    "paintball",
    "mysticism",
    "math",
    "skateboarding",
    "driving",
    "cursing",
    "seeing in color",
    "making friends",
    "sleeping",
    "learning",
    "speaking backwards",
    "acrobatics",
    "mind reading",
    "reading",
    "saving the planet",
    "saving endangered species",
    "day drinking",
    "questioning",
    "believing",
    "loving",
    "listening",
    "dancing like everyone is watching",
    "Fast & Furious movies",
    "voting",
    "shopping",
    "smoking",
    "drinking",
    "bathing",
    "singing",
    "magic tricks",
    "making cookies",
    "wetting pants",
    "growing a mustache",
    "getting taller",
    "getting shorter",
    "living",
    "donating",
    "helping",
    "volunteering",
    "shouting",
    "hurting",
    "writing",
    "making money",
    "saving money",
    "losing money",
    "counterfeiting money",
    "banjo",
    "caring",
    "exercising",
    "exercising demons",
    "having emotions",
    "meet dogs",
    "eating meat",
    "eating veggies",
    "eating fruit",
    "eating glue",
    "drinking paint",
    "enjoying things",
    "world hunger",
    "bad breath",
    "superstitions",
    "spooky things",
    "fasting",
    "helping others",
    "healing the sick",
    "cooking",
    "traveling",
    "tickling",
    "shooting hoops",
    "snorting things",
    "using plastics",
    "Making America Great Again",
    "planting crops",
    "dating",
    "learning to read",
    "using hashtags",
    "break dancing",
    "using calculators",
    "feeling guilty",
    "joining cults",
    "treasure hunting",
    "online shopping",
    "sleepwalking",
    "winning the Hunger Games",
    "fearing death",
    "wrapping gifts",
    "dressing casually",
    "recording episodes of Friends",
    "listening to jazz",
    "bragging",
    "hurting the ones you love",
    "sabotaging",
    "tagging",
    "seeking fortune",
    "telling it like it is",
    "dreaming big",
    "liking",
    "Googling",
    "tap dancing",
    "doing laundry",
    "flushing",
    "running red lights",
    "believing superstitions",
    "being such a coward",
    "teaching algebra",
    "cuddling kittens",
    "body piercing",
    "spitting",
    "scuba diving",
    "shrinking",
    "seafaring",
    "barfing",
    "popping out and scaring people",
    "feeling sad",
    "seeking fame",
    "mountain climbing",
    "feeling sleepy",
    "having visions",
    "fire-eating",
    "acrobatics",
    "vaping",
    "cross-dressing",
    "hula-hooping",
    "crying",
    "sunbathing",
    "pooping outside",
    "switching to LED lighting",
    "fat-shaming pets",
    "writing fan fiction novels",
    "getting the high score",
    "buying boots",
    "diving in a submarine",
    "denying climate change",
    "working on my stand-up routine",
    "working late",
    "waking up early",
    "dropping acid",
    "Bitcoin mining",
    "taking out the trash",
    "smelling what The Rock is cooking",
    "singing sea shanties",
    "generating AI art",
    "tagging and graffiti",
    "getting elected",
    "commiserating",
    "haunting houses",
    "winning the lottery",
    "eating a whole pizza",
    "meeting a celebrity",
    "getting a tattoo",
    "sporting a mullet",
    "getting a perm",
    "worshiping the devil",
    "committing murders",
    "believing in Q-Anon",
    "wearing a mask",
    "getting vaccinated",
    "spreading rumors",
    "hunting pidgins",
    "wandering in the wilderness",
    "getting promoted",
    "finding a job",
    "quitting your job",
    "voluntarily going to prison",
    "owning a dozen houses",
    "buying a car",
    "saving up for a tank",
    "downloading",
    "going insane",
    "driving cars",
    "having babies",
    "organizing a protest",
    "living forever",
    "dieing young",
    "living in a van",
    "developing reptilian features",
    "cutting your own hair",
    "burning bridges",
    "Finding Nemo",
    "cuddling kittens",
    "serving suckers in dance battles",
  ],
  how: [
    "on drugs",
    "before next week",
    "in January",
    "by February",
    "by March",
    "by April",
    "by June",
    "by July",
    "by August",
    "by September",
    "by October",
    "by November",
    "in December",
    "eventually",
    "maybe",
    "someday",
    "tomorrow",
    "pretty soon",
    "if you feel like it",
    "...or not. Who cares?",
    "in space",
    "on the moon",
    "on Mars",
    "orbiting Saturn",
    "for science",
    "for Christ",
    "immediately",
    "right now",
    "next Tuesday",
    "carefully",
    "quickly",
    "Seriously.",
    "everyday",
    "most days",
    "once a month",
    "once a week",
    "twice daily",
    "in the potty",
    "with friends",
    "with family",
    "with neighbors",
    "with animals",
    "for animals",
    "for kids",
    "outside",
    "never",
    "on Netflix",
    "on Amazon",
    "with ghosts",
    "in Europe",
    "in pants",
    "eleven times",
    "fifty times",
    "one hundred times",
    "sixty times",
    "ten times",
    "twice",
    "thrice",
    "a few times",
    "at least once",
    "on airplanes",
    "indoors",
    "every night",
    "with parents",
    "just for fun",
    "and write about it",
    "for myself",
    "around others",
    "around children",
    "around schools",
    "on the streets",
    "around the house",
    "downstairs",
    "by the shed",
    "by moonlight",
    "on the sea",
    "under the sea",
    "upstream",
    "online",
    "on Snapchat",
    "in bed",
    "in the shower",
    "forever",
    "until Friday",
    "until summer",
    "until fall",
    "until winter",
    "to music",
    "in the dark",
    "before my birthday",
    "at an amusement park",
    "before prom",
    "tomorrow",
    "in your imagination",
    "over my dead body",
    "as a joke",
    "once all my baby teeth fall out",
    "once I hit puberty",
    "as soon as I can afford it",
    "to save my life",
    "to impress others",
    "during movies",
    "at the table",
    "for breakfast",
    "audibly",
    "on the dark web",
    "kinda",
    "on horseback",
    "at camp",
    "at school",
    "on Broadway",
    "during pregnancy",
    "with feeling",
    "with new people",
    "on TV",
    "backwards",
    "without supervision",
    "when I grow up",
    "until I lose 100 lbs.",
    "on a game show",
    "until it hurts",
    "with vengeance",
    "with my eyes closed",
    "while I'm still young",
    "unless it's too hard",
    "in secret",
    "while blindfolded",
    "on stage",
    "in the nude",
    "twenty years ago",
    "posthaste",
    "on fire",
    "at the zoo",
    "on TikTok",
    "using witchcraft",
    "until I gain 200 lbs.",
    "after Zoom meetings",
    "riding switch",
    "while ghost riding whips",
    "at work",
    "around the office",
    "at the park",
    "in the woods",
    "on a boat",
    "down by the river",
    "in alternate dimensions",
    "over my dead body",
    "under the influence",
    "in the morning",
    "in the afternoon",
    "in the evening",
    "in the middle of the night",
    "in the middle of the day",
    "every Monday",
    "every weekend",
    "before breakfast",
    "in a musical",
    "on the black market",
  ],
};

export default choices;
